substitutions:
  device_name: "power-monitor-outlet"
  friendly_name: "Power Monitoring Outlet"
  output_power: "20"
  project_name: "power-monitor-outlet"
  project_version: "1.0"
  restore_mode: "RESTORE_DEFAULT_ON"

esphome:
  name: "${device_name}"
  name_add_mac_suffix: true
  comment: ${friendly_name}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Configure WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: ${output_power}
  ap: # Enable fallback hotspot in case wifi connection fails
    ssid: "${device_name}"

# Enable captive portal in case wifi connection fails
captive_portal:

# Provides basic web interface and firmware upload capability
web_server:
  include_internal: true

# Enable logging
logger:
  level: INFO
  baud_rate: 0 # Disable logging to serial

# Enable native API
api:

# Enable OTA updates
ota:
  on_error:
    then:
      - button.press: restart_button

# Enable time component for use by daily power sensor
time:
  - platform: homeassistant

# red led, blink when not connected to wifi or Home Assistant
status_led:
    pin:
      number: GPIO0
      inverted: true

binary_sensor:
  # Reports when the button is pressed
  - platform: gpio
    name: ${friendly_name} Button
    device_class: power
    pin:
      number: GPIO13
      inverted: True
    filters:
      - delayed_on: 100ms
    on_press:
      - switch.toggle: relay

sensor:
  # Reports the Current, Voltage, and Power used by the plugged-in device (not counting this plug's own usage of about 0.8W/0.019A, so subtract those when calibrating with this plugged into a Kill-A-Watt type meter)
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO5
    cf1_pin: GPIO14
    power:
      name: ${friendly_name} Power
      unit_of_measurement: W
      id: power_sensor
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0 #Need to keep 0 mapped to 0 for when connected device is not drawing any power
            - 113 -> 20
            - 3543 -> 617
            - 6660 -> 1155
        - delta: 5.0
    current:
      name: ${friendly_name} Current
      id: current_sensor
      unit_of_measurement: A
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0 #Need to keep 0 mapped to 0 for when connected device is not drawing any power
            - 0.27 -> 0.3
            - 6.81 -> 5.35
            - 12.73 -> 10.28
        - delta: 0.25
    voltage:
      name: ${friendly_name} Voltage
      id: voltage_sensor
      unit_of_measurement: V
      filters:
        - calibrate_linear:
            - 303.7 -> 118.2
            - 299.7 -> 114.8
            - 285.2 -> 111.3
        - delta: 1.0
    change_mode_every: 1 #Skips first reading after each change, so this will double the update interval. Default 8
    update_interval: 5s #10 second effective update rate for Power, 20 second for Current and Voltage. Default 60s

  # Reports the total Power so-far each day, resets at midnight, see https://esphome.io/components/sensor/total_daily_energy.html
  - platform: total_daily_energy
    name: ${friendly_name} Total Daily Energy
    power_id: power_sensor
    filters:
      - multiply: 0.001 ## convert Wh to kWh
    unit_of_measurement: kWh

  # WiFi Signal Strength
  - platform: wifi_signal
    name: "${friendly_name} WiFi RSSI"
    update_interval: 10s
    filters:
      - sliding_window_moving_average:
          window_size: 12
          send_every: 6
      - delta: 2.0

switch:
  - platform: gpio
    name: ${friendly_name}
    device_class: outlet
    icon: mdi:power-plug
    pin: GPIO15
    id: relay
    restore_mode: ${restore_mode}
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    name: "${friendly_name} Blue LED"
    id: blue_led
    internal: true
    pin:
      number: GPIO2
      inverted: true

# Reboot
button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart Firmware"
    disabled_by_default: true
